version: '3.0'
services:
    
  mongo1:
    image: docker.io/bitnami/mongodb:4.4
    ports:
      - 27018:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=hiperiondevelreplicaset
      - MONGODB_REPLICA_SET_KEY=HIPERIONDEVKEY
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_DATABASE=test
    volumes:
      - ./data/mongo:/bitnami/mongodb

  mongo2:
    image: docker.io/bitnami/mongodb:4.4
    ports:
      - 27019:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo2
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_KEY=HIPERIONDEVKEY
      - MONGODB_INITIAL_PRIMARY_HOST=mongo1
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=root
    depends_on:
      - mongo1

  mongo3:
    image: docker.io/bitnami/mongodb:4.4
    ports:
      - 27020:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo3
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_KEY=HIPERIONDEVKEY
      - MONGODB_INITIAL_PRIMARY_HOST=mongo1
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=root
    depends_on:
      - mongo1
  